// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('20251003 Review', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('20251003 Review', async function() {
    while(!!await driver.executeScript("return (true)")) {
      await driver.get("https://kinerja.jabarprov.go.id/kinerjajabar/review-perilaku")
      if (!!await driver.executeScript("return (driver.findElement(By.linkText(\'Lakukan Review\')) != null)")) {
        await driver.findElement(By.linkText("Lakukan Review")).click()
        await driver.findElement(By.css(".flex:nth-child(1) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".flex:nth-child(2) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".flex:nth-child(3) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".flex:nth-child(4) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".flex:nth-child(5) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".flex:nth-child(6) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".flex:nth-child(7) > .flex > .flex > .hidden > .bg-white:nth-child(6)")).click()
        await driver.findElement(By.css(".button-green > span")).click()
      } else {
      }
  })
})
