# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.common.exceptions import TimeoutException, StaleElementReferenceException

class Test20250803Review():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_20250803Review(self):
    self.driver.get("https://kinerja.jabarprov.go.id/kinerjajabar/review-perilaku")
    
    # Loop: when "Lakukan Review" exists, click it, select all "Selalu", save, return, repeat
    while True:
      try:
        link = WebDriverWait(self.driver, 3).until(
          expected_conditions.element_to_be_clickable((By.LINK_TEXT, "Lakukan Review"))
        )
      except TimeoutException:
        break

      link.click()
      try:
        WebDriverWait(self.driver, 5).until(expected_conditions.staleness_of(link))
      except TimeoutException:
        pass

      # On the review page: click seven "Selalu" options
      def click_buttons_with_text(text, expected_count=7, timeout=10):
        # Try repeatedly until enough clicks are done or timeout
        clicks_done = 0
        start = 0
        while clicks_done < expected_count:
          try:
            buttons = self.driver.find_elements(By.XPATH, f"//*[normalize-space(text())='{text}']")
            # Click remaining needed
            for btn in buttons:
              if clicks_done >= expected_count:
                break
              try:
                self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", btn)
                WebDriverWait(self.driver, 5).until(expected_conditions.element_to_be_clickable(btn))
                btn.click()
                clicks_done += 1
              except StaleElementReferenceException:
                # Re-find and try again once
                refind = self.driver.find_elements(By.XPATH, f"//*[normalize-space(text())='{text}']")
                if start < len(refind):
                  try:
                    target = refind[start]
                    self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", target)
                    WebDriverWait(self.driver, 3).until(expected_conditions.element_to_be_clickable(target))
                    target.click()
                    clicks_done += 1
                  except Exception:
                    pass
                start += 1
            if clicks_done < expected_count:
              # brief yield before next attempt
              WebDriverWait(self.driver, 0.5)
          except Exception:
            # ignore and retry until timeout logic above breaks loop
            pass
        return clicks_done

      click_buttons_with_text("Selalu", expected_count=7)

      # Click "Simpan"
      try:
        save_btn = WebDriverWait(self.driver, 5).until(
          expected_conditions.element_to_be_clickable((By.XPATH, "//*[normalize-space(text())='Simpan']"))
        )
      except TimeoutException:
        # fallback to previous CSS selector
        save_btn = WebDriverWait(self.driver, 5).until(
          expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".button-green, .button-green > span"))
        )
      self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", save_btn)
      save_btn.click()

      # Handle possible confirmation modal
      try:
        # try a confirm text button commonly used
        confirm = WebDriverWait(self.driver, 4).until(
          expected_conditions.element_to_be_clickable((By.XPATH, "//*[normalize-space(text())='Ya' or normalize-space(text())='OK' or contains(@class,'text-green')]"))
        )
        confirm.click()
      except TimeoutException:
        pass

      # Wait until redirected back to the listing page
      try:
        WebDriverWait(self.driver, 10).until(lambda d: "/review-perilaku" in d.current_url)
      except TimeoutException:
        pass
  
